---
- name: Install Jenkins on servers
  hosts: all
  become: true
  remote_user: ubuntu

  vars:
    efs_mount_dir: "/data"
    efs_mount_point: "fs-0902f45cd1a39cdcd.efs.us-west-2.amazonaws.com"
    jenkins_version: "2.387.1"

  roles:
    - jenkins
