---
- name: Install Jenkins
  apt:
    name: jenkins=2.387.1
    state: latest

- name: Manage Jenkins via systemd
  systemd:
    name: jenkins
    enabled: yes
    state: started

- name: Change Jenkins data directory to /data
  lineinfile:
    path: /etc/default/jenkins
    regexp: '^JENKINS_HOME='
    line: 'JENKINS_HOME="/data"'
    state: present