---
- hosts: load-balancer
  remote_user: ubuntu
  become: yes

  roles:
    - load-balancer

  vars:
    consul_template_url: "https://releases.hashicorp.com/consul-template/0.30.0/consul-template_0.30.0_linux_amd64.zip"