---
  - name: Update and upgrade apt packages
    become: true
    apt:
        upgrade: yes
        update_cache: yes

  - name: Install JRE
    become: true
    apt:
      name: openjdk-17-jre
      state: latest

  - name: Install maven
    package:
        name: maven
        state: latest

  - name: Set permissions for /opt
    file:
        path: /opt
        mode: 0755
        state: directory