---
  - name: Update and upgrade apt packages
    become: true
    apt:
      upgrade: yes
      update_cache: yes
  
  - name: Install Consul Server
    apt: 
      name: consul 
      state: latest
  
  - name: Start Consul Agent Template
    shell: consul agent -dev -config-dir /etc/consul.d/ &
    register: consul_start
    ignore_errors: true

