---
  - name: Update and upgrade apt packages
    become: true
    apt:
      upgrade: yes
      update_cache: yes
  
  - name: Install Nginx on Server
    apt: 
      name: nginx 
      state: latest
  
  - name: Copy Nginx Index HTML 
    template:
      src: index.html
      dest: /usr/share/nginx/html/index.html 
  
  - name: Start and enable a service
    service:
      name: nginx
      state: started
      enabled: yes
