---
  - name: Update and upgrade apt packages
    become: true
    apt:
      upgrade: yes
      update_cache: yes
  
  - name: Install Consul Server
    apt: 
      name: consul 
      state: latest
  
  - name: Render Consul Configuration Template
    template:
      src: config.json.j2
      dest: /etc/consul.d/consul.json
    vars:
      bind_addr: 0.0.0.0
      data_dir: /var/consul
      datacenter: dc1
      ui: true
      leave_on_terminate: true
      retry_join:
        - server01
      server: true
      log_level: INFO
  
  - name: Start Consul Server
    shell: consul agent -config-dir /etc/consul.d/
    args:
      creates: /var/run/consul.pid
